// =============================================================================
// RestaurantFlow — Consumption History Page
// Phase 11
//
// Shows inventory consumption batches with filters by branch/date/status.
// Allows reversal of completed batches (with permission).
// =============================================================================

import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useConsumptionBatches, useReverseConsumption } from '@/hooks/useRecipes'
import type { ConsumptionListParams, BatchStatus } from '@/types'
import { useAuth } from '@/contexts/AuthContext'

const BATCH_STATUS_BADGE: Record<BatchStatus, string> = {
  PENDING:    'bg-gray-500/10 text-gray-400 border-gray-500/20',
  PROCESSING: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  COMPLETED:  'bg-green-500/10 text-green-400 border-green-500/20',
  FAILED:     'bg-red-500/10 text-red-400 border-red-500/20',
  REVERSED:   'bg-amber-500/10 text-amber-400 border-amber-500/20',
}

export function ConsumptionHistoryPage() {
  const { user, hasPermission } = useAuth()
  const [params, setParams] = useState<ConsumptionListParams>({})
  const [branchFilter, setBranchFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState<BatchStatus | ''>('')
  const [dateFilter, setDateFilter] = useState('')
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [actionError, setActionError] = useState<string | null>(null)
  const [reversalReason, setReversalReason] = useState('')

  const queryParams: ConsumptionListParams = {}
  if (branchFilter) queryParams.branch = branchFilter
  if (statusFilter) queryParams.status = statusFilter
  if (dateFilter) queryParams.date = dateFilter

  const { data: batches = [], isLoading, error, refetch } = useConsumptionBatches(queryParams)
  const reverse = useReverseConsumption()

  const handleReverse = async (batchId: string) => {
    if (!reversalReason.trim()) { setActionError('Please enter a reason for reversal.'); return }
    if (!confirm('Reverse this consumption? Stock will be returned.')) return
    setActionError(null)
    try {
      await reverse.mutateAsync({ id: batchId, reason: reversalReason })
      setReversalReason('')
      setExpandedId(null)
    } catch (e: any) {
      setActionError(e?.response?.data?.message ?? 'Failed to reverse consumption')
    }
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-white">Consumption History</h1>
        <p className="text-sm text-gray-400 mt-1">
          Inventory consumption batches generated by kitchen orders
        </p>
      </div>

      {/* Filters */}
      <div className="flex gap-3 flex-wrap">
        <input
          type="date"
          value={dateFilter}
          onChange={e => setDateFilter(e.target.value)}
          className="bg-gray-800 border border-gray-700 text-white rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-brand-500"
        />
        <select
          value={statusFilter}
          onChange={e => setStatusFilter(e.target.value as BatchStatus | '')}
          className="bg-gray-800 border border-gray-700 text-white rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-brand-500"
        >
          <option value="">All statuses</option>
          <option value="COMPLETED">Completed</option>
          <option value="FAILED">Failed</option>
          <option value="REVERSED">Reversed</option>
          <option value="PENDING">Pending</option>
        </select>
        <button
          onClick={() => { setBranchFilter(''); setStatusFilter(''); setDateFilter('') }}
          className="text-gray-400 hover:text-white text-sm px-3 py-2"
        >
          Clear
        </button>
      </div>

      {actionError && (
        <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-3 text-red-400 text-sm">{actionError}</div>
      )}

      {/* Batches */}
      {isLoading ? (
        <div className="text-gray-400 text-sm">Loading consumption history…</div>
      ) : error ? (
        <div className="text-red-400 text-sm">Failed to load consumption history.</div>
      ) : batches.length === 0 ? (
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-8 text-center text-gray-400">
          No consumption records found.
        </div>
      ) : (
        <div className="space-y-3">
          {batches.map(batch => (
            <div key={batch.id} className="bg-gray-800 border border-gray-700 rounded-xl overflow-hidden">
              {/* Batch header row */}
              <div
                className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-gray-700/30"
                onClick={() => setExpandedId(expandedId === batch.id ? null : batch.id)}
              >
                <div className="flex items-center gap-4">
                  <span className={`inline-flex px-2 py-0.5 rounded border text-xs font-medium ${BATCH_STATUS_BADGE[batch.status]}`}>
                    {batch.status}
                  </span>
                  <div>
                    <span className="text-white text-sm font-medium">
                      {batch.order_number ?? 'Manual'}
                    </span>
                    <span className="text-gray-500 text-xs ml-2">{batch.branch_name}</span>
                  </div>
                  <span className="text-gray-400 text-xs">
                    {batch.consumption_count} item{batch.consumption_count !== 1 ? 's' : ''}
                  </span>
                  <span className="text-brand-400 text-sm font-medium">₹{batch.total_cost}</span>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-gray-500 text-xs">
                    {new Date(batch.triggered_at).toLocaleString()}
                  </span>
                  <svg
                    className={`w-4 h-4 text-gray-400 transition-transform ${expandedId === batch.id ? 'rotate-180' : ''}`}
                    fill="none" viewBox="0 0 24 24" stroke="currentColor"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </div>

              {/* Expanded: consumption items */}
              {expandedId === batch.id && (
                <div className="border-t border-gray-700">
                  {batch.status === 'FAILED' && batch.failure_reason && (
                    <div className="px-4 py-2 bg-red-500/5 border-b border-gray-700">
                      <span className="text-red-400 text-xs">
                        <strong>Failure reason:</strong> {batch.failure_reason}
                      </span>
                    </div>
                  )}

                  {/* We show the summary from the list — clicking into detail loads full items */}
                  <div className="px-4 py-3">
                    <div className="flex items-center justify-between mb-2">
                      <p className="text-xs text-gray-500">
                        Trigger: <span className="text-gray-400">{batch.trigger}</span>
                        {batch.triggered_by_email && (
                          <span className="ml-2">by <span className="text-gray-400">{batch.triggered_by_email}</span></span>
                        )}
                      </p>
                      {batch.order && (
                        <Link
                          to={`/orders/${batch.order}`}
                          className="text-brand-400 hover:text-brand-300 text-xs"
                          onClick={e => e.stopPropagation()}
                        >
                          View Order →
                        </Link>
                      )}
                    </div>

                    {/* Reversal */}
                    {batch.status === 'COMPLETED' && hasPermission('inventory.consumption.reverse') && (
                      <div className="mt-3 pt-3 border-t border-gray-700/50">
                        <p className="text-xs text-gray-400 mb-2">Reverse this consumption (returns stock):</p>
                        <div className="flex gap-2">
                          <input
                            type="text"
                            value={reversalReason}
                            onChange={e => setReversalReason(e.target.value)}
                            placeholder="Reason for reversal…"
                            className="flex-1 bg-gray-700 border border-gray-600 text-white rounded px-2 py-1.5 text-xs focus:outline-none"
                            onClick={e => e.stopPropagation()}
                          />
                          <button
                            onClick={e => { e.stopPropagation(); handleReverse(batch.id) }}
                            className="bg-amber-600/20 border border-amber-500/20 text-amber-400 hover:bg-amber-600/30 px-3 py-1.5 rounded text-xs font-medium"
                          >
                            Reverse
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
