# =============================================================================
# RestaurantFlow — CRM Models
# Phase 17: Customer Management, CRM, Loyalty & Feedback
#
# Models:
#   CustomerSequence          — concurrency-safe customer number generator
#   Customer                  — core customer profile (company + restaurant scoped)
#   CustomerPreference        — customer-provided preferences
#   CustomerVisit             — visit tracking (idempotent, order-referenced)
#   CustomerTag               — restaurant-defined tags
#   CustomerTagAssignment     — customer ↔ tag assignment
#   CustomerSegment           — criteria-based segmentation definitions
#   CustomerSegmentAssignment — customer ↔ segment assignment with audit snapshot
#   LoyaltyProgram            — restaurant-scoped loyalty program
#   LoyaltyAccount            — per-customer loyalty balance
#   LoyaltyTransaction        — immutable ledger (EARN/REDEEM/BONUS/ADJUSTMENT/EXPIRY/REVERSAL)
#   LoyaltyReward             — reward definitions
#   RewardRedemption          — redemption records
#   CustomerFeedback          — customer ratings and comments
#   FeedbackModeration        — moderation workflow for feedback
#   CustomerConsent           — customer communication consent records
#   CustomerConsentHistory    — immutable consent history
#   CustomerMergeRequest      — controlled merge approval workflow
#   CRMAuditLog               — append-only audit trail for CRM actions
#
# Design principles:
#   - UUID primary keys on all business models.
#   - TimestampedModel base for created_at / updated_at.
#   - PROTECT foreign keys — no accidental cascade deletion.
#   - All monetary values use DecimalField — never float.
#   - Loyalty balance changes are ONLY made through the service layer.
#   - Audit logs are immutable (save() guard like existing apps).
#   - Company / restaurant / branch scope enforced in service layer.
#   - Never duplicate Order / Bill / Payment models.
# =============================================================================

import uuid
import logging

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from core.models import TimestampedModel
from crm.constants import (
    GENDER_CHOICES,
    DIETARY_CHOICES,
    VISIT_TYPE_CHOICES, VISIT_STATUS_CHOICES, VISIT_OPEN,
    LOYALTY_TRANSACTION_TYPE_CHOICES,
    REWARD_TYPE_CHOICES,
    REDEMPTION_STATUS_CHOICES, REDEMPTION_REQUESTED,
    FEEDBACK_STATUS_CHOICES, FEEDBACK_SUBMITTED,
    MODERATION_STATUS_CHOICES, MODERATION_PENDING,
    CONSENT_TYPE_CHOICES, CONSENT_STATUS_CHOICES, CONSENT_SOURCE_CHOICES,
    MERGE_STATUS_CHOICES, MERGE_REQUESTED,
    AUDIT_EVENT_CHOICES,
)

logger = logging.getLogger("crm")


# =============================================================================
# CustomerSequence
# =============================================================================

class CustomerSequence(TimestampedModel):
    """
    Concurrency-safe customer number sequence per restaurant.

    Format: CUS-{seq:06d}

    Uses select_for_update() in the service — never MAX()+1.
    One row per restaurant.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    restaurant = models.OneToOneField(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customer_sequence",
        db_index=True,
    )

    last_sequence = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = "Customer Sequence"
        verbose_name_plural = "Customer Sequences"

    def __str__(self):
        return f"CustomerSeq restaurant={self.restaurant.name} seq={self.last_sequence}"


# =============================================================================
# Customer
# =============================================================================

class Customer(TimestampedModel):
    """
    Core customer profile.

    Scoped to company (Organization) + restaurant. A customer is identified
    within a restaurant scope — the same physical person may have separate
    customer records in different restaurants (intentional: no cross-restaurant
    merging without controlled workflow).

    Identity fields (phone, email) are normalized before matching.

    Computed statistics (total_visits, total_orders, lifetime_spend, etc.)
    are NEVER trusted from frontend input. They are updated exclusively by
    CustomerStatisticsService.

    customer_number is immutable after creation. Generated by CustomerService
    using CustomerSequence.select_for_update().
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # -------------------------------------------------------------------------
    # Scope
    # -------------------------------------------------------------------------
    company = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.PROTECT,
        related_name="customers",
        db_index=True,
    )
    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customers",
        db_index=True,
    )

    # -------------------------------------------------------------------------
    # Identity
    # -------------------------------------------------------------------------
    customer_number = models.CharField(
        max_length=30,
        db_index=True,
        help_text="Human-readable, immutable identifier. Format: CUS-000001.",
    )

    # -------------------------------------------------------------------------
    # Personal details
    # -------------------------------------------------------------------------
    first_name = models.CharField(max_length=150, db_index=True)
    last_name = models.CharField(max_length=150, blank=True, db_index=True)
    display_name = models.CharField(
        max_length=200,
        blank=True,
        help_text="If blank, derived from first_name + last_name.",
    )
    phone = models.CharField(
        max_length=30,
        blank=True,
        db_index=True,
        help_text="Normalized E.164-style phone.",
    )
    email = models.EmailField(
        blank=True,
        db_index=True,
        help_text="Normalized lowercase email.",
    )
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        blank=True,
    )

    # -------------------------------------------------------------------------
    # Address
    # -------------------------------------------------------------------------
    address = models.TextField(blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=100, blank=True, default="India")

    # -------------------------------------------------------------------------
    # Internal notes
    # -------------------------------------------------------------------------
    notes = models.TextField(blank=True)
    preferred_language = models.CharField(max_length=10, blank=True)

    # -------------------------------------------------------------------------
    # Status
    # -------------------------------------------------------------------------
    is_active = models.BooleanField(default=True, db_index=True)
    is_blocked = models.BooleanField(default=False, db_index=True)
    blocked_reason = models.TextField(blank=True)

    # -------------------------------------------------------------------------
    # Computed statistics — NEVER set from frontend; only from services
    # -------------------------------------------------------------------------
    total_visits = models.PositiveIntegerField(default=0)
    total_orders = models.PositiveIntegerField(default=0)
    lifetime_spend = models.DecimalField(
        max_digits=14, decimal_places=2, default="0.00",
    )
    last_visit_at = models.DateTimeField(null=True, blank=True, db_index=True)
    last_order_at = models.DateTimeField(null=True, blank=True, db_index=True)
    first_order_at = models.DateTimeField(null=True, blank=True)

    # -------------------------------------------------------------------------
    # Soft-delete / merge tracking
    # -------------------------------------------------------------------------
    merged_into = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="merged_sources",
        help_text="Set when this customer was merged into another.",
    )

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["restaurant", "customer_number"],
                name="unique_customer_number_per_restaurant",
            ),
        ]
        indexes = [
            models.Index(fields=["company", "restaurant"]),
            models.Index(fields=["restaurant", "is_active"]),
            models.Index(fields=["restaurant", "is_blocked"]),
            models.Index(fields=["restaurant", "created_at"]),
            models.Index(fields=["phone"]),
            models.Index(fields=["email"]),
            models.Index(fields=["last_order_at"]),
            models.Index(fields=["last_visit_at"]),
            models.Index(fields=["is_active", "is_blocked"]),
            models.Index(fields=["company", "phone"]),
            models.Index(fields=["restaurant", "phone"]),
            models.Index(fields=["restaurant", "email"]),
        ]

    def __str__(self):
        return f"{self.customer_number} — {self.effective_display_name}"

    @property
    def effective_display_name(self) -> str:
        if self.display_name:
            return self.display_name
        full = f"{self.first_name} {self.last_name}".strip()
        return full or self.customer_number

    @property
    def masked_phone(self) -> str:
        if not self.phone:
            return ""
        return f"******{self.phone[-4:]}" if len(self.phone) > 4 else "****"

    @property
    def masked_email(self) -> str:
        if not self.email:
            return ""
        parts = self.email.split("@")
        if len(parts) != 2:
            return "****"
        local, domain = parts
        masked_local = local[0] + "*" * (len(local) - 1) if local else "*"
        return f"{masked_local}@{domain}"


# =============================================================================
# CustomerPreference
# =============================================================================

class CustomerPreference(TimestampedModel):
    """
    Customer-provided preferences within a restaurant scope.

    These are explicit preferences supplied by or on behalf of the customer.
    Never infer sensitive data (e.g. dietary preference) from order history.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.OneToOneField(
        Customer,
        on_delete=models.CASCADE,
        related_name="preference",
    )
    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customer_preferences",
        db_index=True,
    )

    preferred_order_type = models.CharField(max_length=20, blank=True)
    preferred_branch = models.ForeignKey(
        "organizations.Branch",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="preferred_customers",
    )
    favorite_category = models.ForeignKey(
        "menu.MenuCategory",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    favorite_menu_item = models.ForeignKey(
        "menu.MenuItem",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    dietary_preference = models.CharField(
        max_length=20,
        choices=DIETARY_CHOICES,
        blank=True,
    )
    allergy_note = models.TextField(blank=True)
    special_request_note = models.TextField(blank=True)

    class Meta:
        verbose_name = "Customer Preference"
        verbose_name_plural = "Customer Preferences"
        indexes = [
            models.Index(fields=["restaurant"]),
        ]

    def __str__(self):
        return f"Preferences — {self.customer.customer_number}"


# =============================================================================
# CustomerVisit
# =============================================================================

class CustomerVisit(TimestampedModel):
    """
    Tracks a single customer visit to a restaurant branch.

    Idempotency: keyed on `order` — one qualifying order produces at most
    one CustomerVisit. The service checks for an existing visit before creating.

    Do NOT create visits for DRAFT or CANCELLED orders.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="visits",
        db_index=True,
    )
    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customer_visits",
        db_index=True,
    )
    branch = models.ForeignKey(
        "organizations.Branch",
        on_delete=models.PROTECT,
        related_name="customer_visits",
        db_index=True,
    )

    # Idempotency reference — one order = at most one visit
    order = models.OneToOneField(
        "orders.Order",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="customer_visit",
    )
    table_session = models.ForeignKey(
        "orders.TableSession",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="customer_visits",
    )

    visit_number = models.PositiveIntegerField(
        default=1,
        help_text="Sequential visit number for this customer at this restaurant.",
    )
    visit_started_at = models.DateTimeField(db_index=True)
    visit_completed_at = models.DateTimeField(null=True, blank=True)
    guest_count = models.PositiveIntegerField(default=1)

    visit_type = models.CharField(
        max_length=20,
        choices=VISIT_TYPE_CHOICES,
        db_index=True,
    )
    status = models.CharField(
        max_length=20,
        choices=VISIT_STATUS_CHOICES,
        default=VISIT_OPEN,
        db_index=True,
    )

    class Meta:
        verbose_name = "Customer Visit"
        verbose_name_plural = "Customer Visits"
        ordering = ["-visit_started_at"]
        indexes = [
            models.Index(fields=["customer", "restaurant"]),
            models.Index(fields=["customer", "visit_started_at"]),
            models.Index(fields=["branch", "visit_started_at"]),
            models.Index(fields=["restaurant", "status"]),
        ]

    def __str__(self):
        return (
            f"Visit #{self.visit_number} — {self.customer.customer_number} "
            f"@ {self.branch.name} [{self.status}]"
        )


# =============================================================================
# CustomerTag
# =============================================================================

class CustomerTag(TimestampedModel):
    """
    Restaurant-defined label that can be applied to customers.

    Tags are managed by staff. Examples: VIP, REGULAR, HIGH_VALUE, INACTIVE.
    Tags and Segments are different:
      - Tags: manually assigned labels
      - Segments: criteria-based auto-classifications
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customer_tags",
        db_index=True,
    )
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, db_index=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True, db_index=True)

    class Meta:
        verbose_name = "Customer Tag"
        verbose_name_plural = "Customer Tags"
        constraints = [
            models.UniqueConstraint(
                fields=["restaurant", "code"],
                name="unique_tag_code_per_restaurant",
            ),
        ]
        indexes = [
            models.Index(fields=["restaurant", "is_active"]),
        ]

    def __str__(self):
        return f"{self.code} ({self.restaurant.name})"


# =============================================================================
# CustomerTagAssignment
# =============================================================================

class CustomerTagAssignment(TimestampedModel):
    """
    Assignment of a CustomerTag to a Customer.

    Uniqueness: one active assignment per customer/tag pair.
    Expired or inactive assignments are retained for history.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="tag_assignments",
        db_index=True,
    )
    tag = models.ForeignKey(
        CustomerTag,
        on_delete=models.PROTECT,
        related_name="assignments",
        db_index=True,
    )
    assigned_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="tag_assignments_made",
    )
    assigned_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)

    class Meta:
        verbose_name = "Customer Tag Assignment"
        verbose_name_plural = "Customer Tag Assignments"
        constraints = [
            models.UniqueConstraint(
                fields=["customer", "tag"],
                condition=models.Q(is_active=True),
                name="unique_active_tag_per_customer",
            ),
        ]
        indexes = [
            models.Index(fields=["customer", "is_active"]),
            models.Index(fields=["tag", "is_active"]),
        ]

    def __str__(self):
        return f"{self.customer.customer_number} — {self.tag.code} [active={self.is_active}]"


# =============================================================================
# CustomerSegment
# =============================================================================

class CustomerSegment(TimestampedModel):
    """
    Criteria-based customer segmentation definition.

    Criteria is stored as JSON. Examples:
        {"min_orders": 10}
        {"min_lifetime_spend": 50000}
        {"days_since_last_order": 60}

    Segmentation is evaluated deterministically by CustomerSegmentationService.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customer_segments",
        db_index=True,
    )
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, db_index=True)
    description = models.TextField(blank=True)
    criteria = models.JSONField(
        default=dict,
        help_text=(
            "Segmentation criteria as JSON. "
            "Keys: min_orders, min_lifetime_spend, days_since_last_order, "
            "max_days_since_last_order, min_visits."
        ),
    )
    is_active = models.BooleanField(default=True, db_index=True)

    class Meta:
        verbose_name = "Customer Segment"
        verbose_name_plural = "Customer Segments"
        constraints = [
            models.UniqueConstraint(
                fields=["restaurant", "code"],
                name="unique_segment_code_per_restaurant",
            ),
        ]
        indexes = [
            models.Index(fields=["restaurant", "is_active"]),
        ]

    def __str__(self):
        return f"{self.code} ({self.restaurant.name})"


# =============================================================================
# CustomerSegmentAssignment
# =============================================================================

class CustomerSegmentAssignment(TimestampedModel):
    """
    Assignment of a CustomerSegment to a Customer.

    Stores the criteria snapshot used for evaluation (audit/debugging).
    Only one active assignment per customer/segment pair is allowed.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="segment_assignments",
        db_index=True,
    )
    segment = models.ForeignKey(
        CustomerSegment,
        on_delete=models.PROTECT,
        related_name="assignments",
        db_index=True,
    )
    assigned_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    evaluation_snapshot = models.JSONField(
        default=dict,
        help_text="Snapshot of customer metrics used during evaluation.",
    )

    class Meta:
        verbose_name = "Customer Segment Assignment"
        verbose_name_plural = "Customer Segment Assignments"
        constraints = [
            models.UniqueConstraint(
                fields=["customer", "segment"],
                condition=models.Q(is_active=True),
                name="unique_active_segment_per_customer",
            ),
        ]
        indexes = [
            models.Index(fields=["customer", "is_active"]),
            models.Index(fields=["segment", "is_active"]),
        ]

    def __str__(self):
        return (
            f"{self.customer.customer_number} → {self.segment.code} "
            f"[active={self.is_active}]"
        )


# =============================================================================
# LoyaltyProgram
# =============================================================================

class LoyaltyProgram(TimestampedModel):
    """
    Restaurant-scoped loyalty program definition.

    Only one active program per restaurant is recommended.
    points_per_currency_unit: how many points earned per 1 unit of spend.
    point_expiry_days: null means points never expire.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="loyalty_programs",
        db_index=True,
    )
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True, db_index=True)

    points_per_currency_unit = models.DecimalField(
        max_digits=8,
        decimal_places=4,
        default="1.0000",
        validators=[MinValueValidator("0.0001")],
        help_text="Points earned per 1 currency unit of eligible spend.",
    )
    minimum_redemption_points = models.PositiveIntegerField(
        default=100,
        help_text="Minimum points required before a customer can redeem.",
    )
    point_expiry_days = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Days after earning before points expire. Null = never.",
    )

    class Meta:
        verbose_name = "Loyalty Program"
        verbose_name_plural = "Loyalty Programs"
        indexes = [
            models.Index(fields=["restaurant", "is_active"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.restaurant.name})"


# =============================================================================
# LoyaltyAccount
# =============================================================================

class LoyaltyAccount(TimestampedModel):
    """
    Per-customer loyalty balance within a loyalty program.

    Points balance is NEVER modified directly — always via LoyaltyService.
    All changes create a LoyaltyTransaction entry first.

    Constraint: points_balance >= 0 enforced in service layer.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="loyalty_accounts",
        db_index=True,
    )
    loyalty_program = models.ForeignKey(
        LoyaltyProgram,
        on_delete=models.PROTECT,
        related_name="accounts",
        db_index=True,
    )

    points_balance = models.PositiveIntegerField(default=0)
    lifetime_points_earned = models.PositiveIntegerField(default=0)
    lifetime_points_redeemed = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = "Loyalty Account"
        verbose_name_plural = "Loyalty Accounts"
        constraints = [
            models.UniqueConstraint(
                fields=["customer", "loyalty_program"],
                name="unique_loyalty_account_per_program",
            ),
        ]
        indexes = [
            models.Index(fields=["customer"]),
            models.Index(fields=["loyalty_program"]),
        ]

    def __str__(self):
        return (
            f"Loyalty: {self.customer.customer_number} "
            f"[{self.loyalty_program.name}] bal={self.points_balance}"
        )


# =============================================================================
# LoyaltyTransaction
# =============================================================================

class LoyaltyTransaction(TimestampedModel):
    """
    Immutable ledger entry for every loyalty balance change.

    Never edit an existing transaction. Every balance change MUST:
      1. Create a LoyaltyTransaction
      2. Update LoyaltyAccount.points_balance

    Both steps happen inside transaction.atomic() with select_for_update().

    reference_type + reference_id are used for idempotency:
      - BILL:<bill_uuid> prevents double-awarding from the same bill
      - REDEMPTION:<redemption_uuid> links to a RewardRedemption

    Balance integrity:
        balance_before + points (signed) == balance_after
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    loyalty_account = models.ForeignKey(
        LoyaltyAccount,
        on_delete=models.PROTECT,
        related_name="transactions",
        db_index=True,
    )
    transaction_type = models.CharField(
        max_length=20,
        choices=LOYALTY_TRANSACTION_TYPE_CHOICES,
        db_index=True,
    )

    # Signed: positive for EARN/BONUS, negative for REDEEM/EXPIRY/REVERSAL
    points = models.IntegerField()

    balance_before = models.PositiveIntegerField()
    balance_after = models.PositiveIntegerField()

    reference_type = models.CharField(max_length=50, blank=True, db_index=True)
    reference_id = models.CharField(max_length=100, blank=True, db_index=True)

    reason = models.TextField(blank=True)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="loyalty_transactions_created",
    )

    class Meta:
        verbose_name = "Loyalty Transaction"
        verbose_name_plural = "Loyalty Transactions"
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["loyalty_account", "reference_type", "reference_id"],
                condition=~models.Q(reference_type=""),
                name="unique_loyalty_transaction_per_reference",
            ),
        ]
        indexes = [
            models.Index(fields=["loyalty_account", "created_at"]),
            models.Index(fields=["reference_type", "reference_id"]),
            models.Index(fields=["transaction_type", "created_at"]),
        ]

    def __str__(self):
        return (
            f"LoyaltyTxn [{self.transaction_type}] "
            f"pts={self.points:+d} bal={self.balance_after} "
            f"ref={self.reference_type}:{self.reference_id}"
        )

    def save(self, *args, **kwargs):
        """LoyaltyTransactions are append-only — block updates."""
        if self.pk and LoyaltyTransaction.objects.filter(pk=self.pk).exists():
            raise ValueError(
                "LoyaltyTransaction records are immutable — they cannot be updated."
            )
        super().save(*args, **kwargs)


# =============================================================================
# LoyaltyReward
# =============================================================================

class LoyaltyReward(TimestampedModel):
    """
    Reward definitions that customers can redeem with their loyalty points.

    Rewards are restaurant-scoped definitions. Actual redemption records are
    in RewardRedemption.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="loyalty_rewards",
        db_index=True,
    )
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    reward_type = models.CharField(
        max_length=20,
        choices=REWARD_TYPE_CHOICES,
        db_index=True,
    )
    points_required = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
    )

    # For DISCOUNT / PERCENTAGE reward types
    reward_value = models.DecimalField(
        max_digits=10, decimal_places=2,
        null=True, blank=True,
    )
    discount_type = models.CharField(max_length=20, blank=True)
    discount_value = models.DecimalField(
        max_digits=10, decimal_places=2,
        null=True, blank=True,
    )
    max_discount_amount = models.DecimalField(
        max_digits=10, decimal_places=2,
        null=True, blank=True,
    )

    is_active = models.BooleanField(default=True, db_index=True)
    valid_from = models.DateTimeField(null=True, blank=True)
    valid_until = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Loyalty Reward"
        verbose_name_plural = "Loyalty Rewards"
        ordering = ["points_required"]
        indexes = [
            models.Index(fields=["restaurant", "is_active"]),
            models.Index(fields=["valid_until"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.points_required} pts) [{self.restaurant.name}]"


# =============================================================================
# RewardRedemption
# =============================================================================

class RewardRedemption(TimestampedModel):
    """
    Record of a customer redeeming a LoyaltyReward.

    Points are deducted atomically via LoyaltyService. The redemption record
    is created in the same transaction as the LoyaltyTransaction(REDEEM).

    reference_code is a short human-readable code for POS use.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.PROTECT,
        related_name="reward_redemptions",
        db_index=True,
    )
    loyalty_account = models.ForeignKey(
        LoyaltyAccount,
        on_delete=models.PROTECT,
        related_name="redemptions",
        db_index=True,
    )
    reward = models.ForeignKey(
        LoyaltyReward,
        on_delete=models.PROTECT,
        related_name="redemptions",
        db_index=True,
    )

    points_used = models.PositiveIntegerField()

    status = models.CharField(
        max_length=20,
        choices=REDEMPTION_STATUS_CHOICES,
        default=REDEMPTION_REQUESTED,
        db_index=True,
    )
    reference_code = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Short code for POS/cashier use.",
    )

    redeemed_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)

    # Optional link to an order/bill where this reward was applied
    applied_to_order = models.ForeignKey(
        "orders.Order",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reward_redemptions",
    )

    class Meta:
        verbose_name = "Reward Redemption"
        verbose_name_plural = "Reward Redemptions"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["customer", "status"]),
            models.Index(fields=["reward", "status"]),
            models.Index(fields=["reference_code"]),
            models.Index(fields=["expires_at"]),
        ]

    def __str__(self):
        return (
            f"Redemption {self.reference_code or self.pk} — "
            f"{self.customer.customer_number} [{self.status}]"
        )


# =============================================================================
# CustomerFeedback
# =============================================================================

class CustomerFeedback(TimestampedModel):
    """
    Customer rating and comment for an order/visit.

    Ratings are integers 1–5. All four rating fields (overall, service,
    food, ambience) are optional except the top-level `rating`.

    If linked to an order, the service validates ownership and eligibility.
    Anonymous feedback is supported (customer = null, order = null).
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="feedback",
        db_index=True,
    )
    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        related_name="customer_feedback",
        db_index=True,
    )
    branch = models.ForeignKey(
        "organizations.Branch",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="customer_feedback",
        db_index=True,
    )
    order = models.OneToOneField(
        "orders.Order",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="customer_feedback",
    )
    visit = models.ForeignKey(
        CustomerVisit,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="feedback",
    )

    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        help_text="Overall rating 1–5.",
    )
    service_rating = models.PositiveSmallIntegerField(
        null=True, blank=True,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )
    food_rating = models.PositiveSmallIntegerField(
        null=True, blank=True,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )
    ambience_rating = models.PositiveSmallIntegerField(
        null=True, blank=True,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )

    comment = models.TextField(blank=True)

    status = models.CharField(
        max_length=20,
        choices=FEEDBACK_STATUS_CHOICES,
        default=FEEDBACK_SUBMITTED,
        db_index=True,
    )

    class Meta:
        verbose_name = "Customer Feedback"
        verbose_name_plural = "Customer Feedback"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["restaurant", "status"]),
            models.Index(fields=["restaurant", "rating"]),
            models.Index(fields=["branch", "status"]),
            models.Index(fields=["customer", "created_at"]),
            models.Index(fields=["created_at"]),
        ]

    def __str__(self):
        cnum = self.customer.customer_number if self.customer else "anon"
        return f"Feedback {self.rating}/5 — {cnum} [{self.status}]"


# =============================================================================
# FeedbackModeration
# =============================================================================

class FeedbackModeration(TimestampedModel):
    """
    Moderation action taken on a CustomerFeedback record.

    Feedback is never silently deleted — status-based moderation only.
    Only one moderation record per feedback at a time (latest wins,
    but all are preserved via append pattern in practice).
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    feedback = models.ForeignKey(
        CustomerFeedback,
        on_delete=models.PROTECT,
        related_name="moderation_records",
        db_index=True,
    )
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="feedback_moderations",
    )
    status = models.CharField(
        max_length=20,
        choices=MODERATION_STATUS_CHOICES,
        default=MODERATION_PENDING,
        db_index=True,
    )
    moderation_note = models.TextField(blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)

    # Optional link to a Central Issue created from this feedback
    central_issue_id = models.UUIDField(
        null=True,
        blank=True,
        help_text="UUID of the CentralIssue created from this feedback, if any.",
    )

    class Meta:
        verbose_name = "Feedback Moderation"
        verbose_name_plural = "Feedback Moderations"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["feedback", "status"]),
            models.Index(fields=["reviewed_by", "created_at"]),
        ]

    def __str__(self):
        return f"Moderation [{self.status}] — feedback={self.feedback_id}"


# =============================================================================
# CustomerConsent
# =============================================================================

class CustomerConsent(TimestampedModel):
    """
    Customer communication consent record.

    One row per customer+consent_type — the current consent state.
    History is preserved in CustomerConsentHistory.

    Marketing communications require explicit GRANTED consent.
    Transactional notifications do not require marketing consent.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="consents",
        db_index=True,
    )
    consent_type = models.CharField(
        max_length=40,
        choices=CONSENT_TYPE_CHOICES,
        db_index=True,
    )
    status = models.CharField(
        max_length=20,
        choices=CONSENT_STATUS_CHOICES,
        db_index=True,
    )
    source = models.CharField(
        max_length=20,
        choices=CONSENT_SOURCE_CHOICES,
        default="CUSTOMER",
    )
    granted_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Customer Consent"
        verbose_name_plural = "Customer Consents"
        constraints = [
            models.UniqueConstraint(
                fields=["customer", "consent_type"],
                name="unique_consent_per_customer_type",
            ),
        ]
        indexes = [
            models.Index(fields=["customer", "status"]),
            models.Index(fields=["consent_type", "status"]),
        ]

    def __str__(self):
        return (
            f"Consent {self.consent_type} [{self.status}] "
            f"— {self.customer.customer_number}"
        )


# =============================================================================
# CustomerConsentHistory
# =============================================================================

class CustomerConsentHistory(TimestampedModel):
    """
    Immutable audit trail for consent changes.

    Created every time a CustomerConsent is updated.
    Never edit or delete these records.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="consent_history",
        db_index=True,
    )
    consent_type = models.CharField(max_length=40, choices=CONSENT_TYPE_CHOICES)
    previous_status = models.CharField(max_length=20, blank=True)
    new_status = models.CharField(max_length=20, choices=CONSENT_STATUS_CHOICES)
    changed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="consent_changes_made",
    )
    source = models.CharField(max_length=20, choices=CONSENT_SOURCE_CHOICES)
    changed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Customer Consent History"
        verbose_name_plural = "Customer Consent Histories"
        ordering = ["-changed_at"]
        indexes = [
            models.Index(fields=["customer", "changed_at"]),
            models.Index(fields=["consent_type", "changed_at"]),
        ]

    def __str__(self):
        return (
            f"ConsentHistory {self.consent_type} "
            f"{self.previous_status}→{self.new_status} "
            f"@ {self.changed_at}"
        )

    def save(self, *args, **kwargs):
        if self.pk and CustomerConsentHistory.objects.filter(pk=self.pk).exists():
            raise ValueError("CustomerConsentHistory records are immutable.")
        super().save(*args, **kwargs)


# =============================================================================
# CustomerMergeRequest
# =============================================================================

class CustomerMergeRequest(TimestampedModel):
    """
    Controlled merge workflow: source customer → target customer.

    Merge requires approval from an authorized user.
    After approval, source customer is deactivated and its history
    is reassigned to the target (via CustomerMergeService).

    Never auto-approve merges. Always require explicit approval.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    source_customer = models.ForeignKey(
        Customer,
        on_delete=models.PROTECT,
        related_name="merge_requests_as_source",
        db_index=True,
    )
    target_customer = models.ForeignKey(
        Customer,
        on_delete=models.PROTECT,
        related_name="merge_requests_as_target",
        db_index=True,
    )
    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="merge_requests_made",
    )
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="merge_requests_approved",
    )
    status = models.CharField(
        max_length=20,
        choices=MERGE_STATUS_CHOICES,
        default=MERGE_REQUESTED,
        db_index=True,
    )
    reason = models.TextField()
    notes = models.TextField(blank=True)

    approved_at = models.DateTimeField(null=True, blank=True)
    rejected_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Customer Merge Request"
        verbose_name_plural = "Customer Merge Requests"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["source_customer", "status"]),
            models.Index(fields=["target_customer", "status"]),
            models.Index(fields=["status", "created_at"]),
        ]

    def __str__(self):
        return (
            f"MergeRequest {self.source_customer.customer_number} → "
            f"{self.target_customer.customer_number} [{self.status}]"
        )


# =============================================================================
# CRMAuditLog
# =============================================================================

class CRMAuditLog(TimestampedModel):
    """
    Immutable append-only audit trail for CRM actions.

    Pattern follows existing per-domain audit logs (PaymentAuditLog,
    FinancialAuditLog, CentralControlAuditLog).

    Never log: passwords, auth tokens, payment card data, provider secrets.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="crm_audit_entries",
        help_text="User who performed the action. Null for system actions.",
    )
    action = models.CharField(
        max_length=60,
        choices=AUDIT_EVENT_CHOICES,
        db_index=True,
    )

    # What was acted on
    entity_type = models.CharField(max_length=50, db_index=True)
    entity_id = models.UUIDField(null=True, blank=True, db_index=True)

    # Scope
    company = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name="crm_audit_logs",
        db_index=True,
    )
    restaurant = models.ForeignKey(
        "organizations.Restaurant",
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name="crm_audit_logs",
    )
    branch = models.ForeignKey(
        "organizations.Branch",
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name="crm_audit_logs",
    )
    customer = models.ForeignKey(
        Customer,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="audit_logs",
        db_index=True,
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Structured data about the action. Never include PII unnecessarily.",
    )

    class Meta:
        verbose_name = "CRM Audit Log"
        verbose_name_plural = "CRM Audit Logs"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["actor", "created_at"]),
            models.Index(fields=["action", "created_at"]),
            models.Index(fields=["entity_type", "entity_id"]),
            models.Index(fields=["company", "created_at"]),
            models.Index(fields=["customer", "created_at"]),
        ]

    def __str__(self):
        return f"CRMAudit: {self.action} on {self.entity_type}:{self.entity_id}"

    def save(self, *args, **kwargs):
        if self.pk and CRMAuditLog.objects.filter(pk=self.pk).exists():
            raise ValueError("CRMAuditLog records are immutable.")
        super().save(*args, **kwargs)
